options:
  max-warnings: 0
files:
  include: 'src/**/*.scss'
formatter:
  - 'stylish'
rules:
  function-name-format:
    - 0
  no-trailing-zero:
    - 0
  leading-zero:
    - 2
    -
      include: true
  nesting-depth:
    - 2
    - max-depth: 4
  no-vendor-prefixes:
    - 1
    - excluded-identifiers:
        - webkit
        - moz
  quotes:
    - 2
    - style: double
  class-name-format:
    - 2
    -
      convention: 'strictbem'
  placeholder-name-format:
    - 2
    -
      convention: 'hyphenatedbem'
  declarations-before-nesting: 2
  empty-args:
    - 1
    -
      include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  force-attribute-nesting: 1
  force-element-nesting: 2
  force-pseudo-nesting: 1
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
  indentation:
    - 2
  property-sort-order:
    - 1
    -
      ignore-custom-properties: true

