export enum Page {
  MAIN = 'MAIN',
  FIND_BOOKS = 'FIND_BOOKS',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  PROFILE = 'PROFILE',
  EDIT_PROFILE = 'EDIT_PROFILE',
  PROFILE_SETTINGS = 'PROFILE_SETTINGS',
  BOOKS = 'BOOKS',
  NEW_BOOK = 'NEW_BOOK',
  BOOK_DETAILS = 'BOOK_DETAILS',
  EDIT_BOOK = 'EDIT_BOOK',
  NOT_FOUND = 'NOT_FOUND'
}
